on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://4aca-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: 659c6b97-b5a7-41cb-b65b-435c0fb12e0a
          repo_url: https://github.com/test-org-pankaj/silver-meme.git